baseURL = 'https://wtong2017.github.io'
languageCode = 'en-us'
title = "Wai TONG's Personal Website"
[params]
    author = 'Wai TONG'
    title = "Assistant Professor"
    university = "Texas A&M University"
[taxonomies]
    publication_type = "publication_types"
    conference = "conferences"
    publication_tag = "publication_tags"
    author = "authors"
    publication_category = "publication_categories"